# Generated by Django 4.1.7 on 2023-03-15 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='descipcion',
            new_name='descripcion',
        ),
    ]
